config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :conversations
  get 'conversation/message' => 'conversations#message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'conversations#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	has_many :messages,dependent: :destroy
	belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	def index
		@conversations = Conversation.all.where('sender_id=? OR receiver_id=?',current_user,current_user)
	end

	def create
		@receiver = User.all.where('email = ?', params[:receiver_email]).first
		#if the receiver is found
		if @receiver
			#if the conversation doesnt existm then create new, else go to their convo.
			if Conversation.all.where('(sender_id=? and receiver_id = ?) OR (sender_id=? and receiver_id=?)',current_user,@receiver ,@receiver, current_user).blank?
				@conversation = Conversation.new
				@conversation.receiver_id = @receiver.id
				@conversation.sender_id = current_user.id
				@conversation.message_count = 1
				@message = params[:message_to_send]
				
				#validation to false due to "user must exist" bug
				if @conversation.save(validate: false)
					#@conversation.messages.create!(user_id: current_user.id, text: params[:message_to_send])
					#render plain: "created successfully"
					@message = params[:message_to_send]
					respond_to do |format|
						format.html{redirect_to root_path}
						format.js
					end	
								
				else
					@conversations = Conversation.all.where('sender_id=? OR receiver_id=?',current_user,current_user)
					render :index
				end
			else
				@conversation = Conversation.all.where('(sender_id=? and receiver_id = ?) OR (sender_id=? and receiver_id=?)',current_user,@receiver ,@receiver, current_user).first
				#@conversation.messages.create!(user_id: current_user.id, text: params[:message_to_send])
				@conversation.message_count = @conversation.message_count + 1
				@message = params[:message_to_send]
				@conversation.save(validate: false)
				respond_to do |format|
					format.html{redirect_to root_path}
					format.js
				end	
				
				#redirect_to @conversation
			end
		else
			redirect_to root_path , alert: "There is no user with that Email address."
		end
	end
	def show
		@conversation = Conversation.find(params[:id])
	end
	def message
		@conversation = Conversation.find(params[:conversation][:conversation_id])
		if current_user == @conversation.sender_id
			@receiver = @conversation.receiver_id
		else
			@receiver = @conversation.sender_id
		end
		@message = params[:message_to_send]
		respond_to do |format|
			format.html{redirect_to @conversation}
			format.js
		end	
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div id = "c_<%= @conversation.id %>" class = "message-holder">
	<% @conversation.messages.each do |message| %>
		<%= render message %>
	<% end %>
</div>

app/views/conversations/create.js.erb
App.conversation.speak("<%= current_user.id %>","<%= @message.html_safe %>","<%= truncate(@message.html_safe, length: 60) %>","<%= @conversation.id %>","<%= @receiver.id %>");

app/views/conversations/index.html.erb
<script>var id = '<%= current_user.id %>'</script>
<div id = "index-container">
	<div id = "side-container">
		<div id = "logo">
			<%= image_tag("quickmessanger-logo.jpg", class: "logo-img") %>
			<div id = "logo-text">QuickMessanger</div>
		</div>	
		<div>
			<%= link_to current_user.email, edit_user_registration_path, id: "regular-button" %>
		</div>
		<div id = "index-connection-status">
		</div>
		<div id = "new-message-button">
			<div id = "regular-button" style = "cursor:pointer">New Message</div>
		</div>
	<div>
		<%= link_to "Sign Out",  destroy_user_session_path ,method: :delete, id: "danger-button" %>
	</div>
</div>
<div class = "conversation-container">
	<div class = "new-message-div">
		<%= form_for(:conversation, url: conversations_path, remote: true) do |f| %>
		<%=	text_field_tag :receiver_email, params[:receiver_email], placeholder: "Recipient Email" %>
		<%= text_area_tag :message_to_send, params[:message_to_send], placeholder: "Message to Send",id: "i" %>
		<div>
			<%= f.submit "Send" %>
		</div>
		<div style = "clear:both">
		</div>
		<% end %>
	</div>
	<div id = "ch_<%= current_user.id %>" class = "conversation-holder">
		<% @conversations.each do |conversation| %>
		<div id = "co_<%= conversation.id %>">
			<%= link_to conversation do %>
			<div class = "conversation">
				<div class = "conversation-1st-row">
					<% if current_user.id == conversation.sender_id %>
					<div style = "float:left;display:inline-block"><%= User.find(conversation.receiver_id).email %></div>
					<% else %>
					<div style = "float:left;display:inline-block"><%= User.find(conversation.sender_id).email %></div>
					<% end %>
					<div style = "float:right;display:inline-block"><%= time_ago_in_words(conversation.messages.last.created_at) %> ago.</div>
					<div style = "clear:both">
					</div>
				</div>
				<div class = "conversation-2nd-row">
					<div style = "padding-left:3rem;color:rgb(155, 174, 200);">
						<%= truncate(conversation.messages.last.text, length: 60) %>
					</div>
				</div>
				<div>
					
				</div>
			</div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>
</div>
<script type="text/javascript">
$("#new-message-button").on("click",function(){
	$(".new-message-div").slideToggle();

});

</script>

app/views/conversations/message.js.erb
//escape needed for "'"
App.conversation.speak("<%= current_user.id %>","<%= @message.html_safe %>","<%= truncate(@message.html_safe, length: 60) %>","<%= @conversation.id %>","<%= @receiver %>");

app/views/conversations/show.html.erb
<script>var id = '<%= current_user.id %>'</script>
<% if (current_user.id == @conversation.receiver_id) or (current_user.id == @conversation.sender_id) %>
<div id = "index-container">
	<div id = "side-container">
		<div id = "logo">
			<%= image_tag("quickmessanger-logo.jpg", class: "logo-img") %>
			<div id = "logo-text">QuickMessanger</div>
		</div>	
		<div>
			<%= link_to current_user.email, edit_user_registration_path, id: "regular-button" %>
		</div>
		<div id = "index-connection-status">
		</div>
		<div>
			<%= link_to "Back", root_path, id: "regular-button" %>
		</div>
		<div>
			<%= link_to "Sign Out",  destroy_user_session_path ,method: :delete, id: "danger-button" %>
		</div>
		
	</div>
	<div class = "conversation-container">
		<%= render @conversation %>
		<div id = "message-input">
			<%= form_for(:conversation, url: conversation_message_path, method: :get, remote: true) do |f|%>
			<%= f.hidden_field :conversation_id, value: @conversation.id %>
			<div class = "show-message-input">
				<%= text_area_tag :message_to_send, params[:message_to_send], id: "i" %>
			</div>
			<div class = "show-submit-button">
				<%= f.submit "send", class: "send-button" %>
			</div>
			<% end %>
		</div>
	</div>
	<div style = "clear:both">
	</div>
	<script>
	$('#i').keypress( function( e ) {
	  if( e.keyCode == 13 ) { $(this).closest('form').trigger('submit'); }
	} );
	</script>
	
</div>
<% else %>
<div style = "text-align:center">
	<h1>Access Denied</h1>
	<div>
		<%= link_to "Back", root_path, id: "regular-button" %>
	</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickMessanger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <% if notice||alert %>
    <div class = "notification">
    	<p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <%= yield %>
    <script>
     $(document).ready(function(){
      setTimeout(function(){
        $('.notification').fadeOut(700,function(){
          $("this").remove();
        });
      },600);
     });
    </script>
  </body>

</html>

app/views/messages/_message.html.erb
<div>
	<% if message.user_id == current_user.id %>
	<br>
	<div class = "my-message">
		<div class = "my-message-user"><%= User.find(message.user_id).email %></div>
		<div style = "float:left;display:inline-block;font-size:0.3rem;"><%= message.created_at.strftime("%m-%d %l:%M %p") %></div>
		<div style = "clear:both">
		</div>
		<div style = "max-width:30rem;">
			<%= message.text %>
		</div>
	</div>
	<% else %>
	<br>
	<div class = "other-message">
		<div class = "other-message-user"><%= User.find(message.user_id).email %></div>
		<div style = "float:right;display:inline-block;font-size:0.3rem;"><%= message.created_at.strftime("%m-%d %l:%M %p") %></div>
		<div style = "clear:both">
		</div>
		<div>
			<%= message.text %>
		</div>
	</div>
	<% end %>
</div>
	